agent_name: ocean_connection
author: maria_oceanprotocol
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.2.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- maria_oceanprotocol/ocean_connection:0.1.0
contracts: []
protocols:
- fetchai/default:1.1.7
- fetchai/signing:1.1.7
- fetchai/state_update:1.1.7
skills: []
default_ledger: fetchai
required_ledgers:
- fetchai
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  aea-ledger-fetchai: {}
default_connection: null
